name: magicmind_puzzle
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.2.2
  google_fonts: ^6.2.1
  fc_native_image_resize: ^0.12.0
  image: ^4.3.0
  image_picker: 
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  mongo_dart: ^0.10.3
  confetti: ^0.8.0
  audioplayers: ^6.2.0
  lottie: ^3.3.1
  intl: ^0.20.2
  shared_preferences: ^2.0.8
  showcaseview:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/audios/

  fonts:
    - family: Andika
      fonts:
        - asset: fonts/Andika-Bold.ttf
        - asset: fonts/Andika-BoldItalic.ttf
        - asset: fonts/Andika-Italic.ttf
        - asset: fonts/Andika-Regular.ttf

    - family: ABeeZee
      fonts:
        - asset: fonts/ABeeZee-Italic.ttf
        - asset: fonts/ABeeZee-Regular.ttf
